---
version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y tar wget unzip sudo
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - mkdir -p /tmp/Solodev
      - fn="$(aws s3 ls s3://solodev-release | sort | tail -n 1 | awk '{print $4}')"
      - aws s3 cp s3://solodev-release/$fn /tmp/Solodev/Solodev.zip
      - unzip /tmp/Solodev/Solodev.zip -d /tmp/Solodev
      - rm -Rf /tmp/Solodev/Solodev.zip
      - ls -al
  build:
    commands:
      - chmod 700 build.sh
      - ./build.sh hashicorp/solodev-phpfpm-72/aws1/config solodev-aws1-packer.json
      - ./build.sh hashicorp/solodev-phpfpm-72/aws1/config solodev-aws1-byol-packer.json
      # - ./build.sh hashicorp/solodev-phpfpm-72/aws2/config solodev-cluster-aws2-packer.json
      - ./build.sh hashicorp/solodev-phpfpm-72/single/config solodev-single-packer.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"